name: me-mudei-api
proxy:
  api:
    - memudei-api.lndo.site:80

services:
  api:
    type: node:14
    app_mount: false
    scanner: false
    ssl: false
    port: 80
    build_as_root:
      - apt-get update -y
      - apt-get install -y jq
    build:
      - npm i -g yarn
    run:
      - yarn deploy:prisma
    command:
      - yarn dev
    overrides:
      environment:
        DATABASE_URL: postgres://postgres@pg:5432/database
        BASE_URL: http://memudei-api.lndo.site
        MAIL_HOST: 'smtp.mailtrap.io'
        MAIL_PORT: '2525'
        MAIL_USER: '73f48fea13f034'
        MAIL_PASS: 'f0dfd88b82236c'
        AUTH0_SECRET: '43ab7d77609e30d6723526fae9ac1b327953338f55bcb6ef18cac04c41d3e969'
        AUTH0_BASE_URL: 'http://memudei-api.lndo.site'
        AUTH0_ISSUER_BASE_URL: 'http://memudei-api.lndo.site'
        AUTH0_DOMAIN: 'dev-r4cyxge8.us.auth0.com'
        AUTH0_CLIENT_ID: 'yHXEEEFlFXxBDoJoM32GouJ7vGhTntXy'
        AUTH0_CLIENT_SECRET: '6dW7sR-pjXo-o7O2Gw6OHmJrMZV7XsptUvXGPHqjZi-bE2kngTpy3an1cMEoTCzW'
        PORT: 80
      ports:
        - 9230:9230
      depends_on:
        - pg
      volumes:
        - ./:/app

  # pg service is a  PostrgresSQL database
  pg:
    build_as_root:
      - chmod -R 777 /tmp
    type: postgres:13
    # can be accessed through the host at http://localhost:7892
    portforward: 7892

events:
  pre-start:
    - pg: rm -f /tmp/.s.PGSQL.5432.lock || true
