services:
  memudei-db:
    container_name: memudei-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: MqzYqy2DpbKZFQj5qM-xF
      POSTGRES_DB: memudei-db
    ports:
      - 11996:5432
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
  s3-localstack:
    container_name: s3-localstack
    image: localstack/localstack
    restart: always
    environment:
      - SERVICES=s3
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - "./.docker/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - ./.docker/localstack:/var/lib/localstack