service: me-mudei-api

package:
  individually: true

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-monorepo
    - serverless-offline

custom:
  node-env:
    prod: "production"
    dev: "development"
    local: "local"
  serverless-offline:
    port: 3000
    stage: local
  serverlessPluginTypescript:
    tsConfigFileLocation: 'tsconfig.build.json'

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30
  memorySize: 512
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  vpc:
    securityGroupIds:
      - ${ssm:/me-mudei/infra/vpc/security-group-ids}
    subnetIds:
      - ${ssm:/me-mudei/infra/vpc/subnet-ids~split}
  environment:
    NODE_ENV: ${self:custom.node-env.${opt:stage}, 'local'}
    SLS_DEBUG: "*"
    LOG_LEVEL: info
    DATABASE_URL: ${env.DATABASE_URL}
    AUTH_VENDOR: ${env.AUTH_VENDOR}
    AUTH_AUDIENCE: ${env.AUTH_AUDIENCE}
    AUTH_ISSUER: ${env.AUTH_ISSUER}
    AUTH_DOMAIN: ${env.AUTH_DOMAIN}
    CLOUD_VENDOR: ${env.CLOUD_VENDOR}
    CLOUD_ACCESS_KEY_ID: ${env.AWS_ACCESS_KEY_ID}
    CLOUD_SECRET_ACCESS_KEY: ${env.AWS_SECRET_ACCESS_KEY}
    CLOUD_REGION: ${env.AWS_REGION}
    CLOUD_ENDPOINT: ${env.CLOUD_ENDPOINT}
    STORAGE_VENDOR: ${env.STORAGE_VENDOR}
    STORAGE_BUCKET: ${env.STORAGE_BUCKET}

functions:
  app:
    handler: src/apollo/src/index-lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
