service: me-mudei-api

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  runtime: nodejs16.x
  memorySize: 512
  vpc:
    securityGroupIds:
      - sg-0e629da5711e30609
    subnetIds:
      - subnet-02f16aeed6f53b362
      - subnet-0299b2dde70727453
  #ecr:
  #  # In this section you can define images that will be built locally and uploaded to ECR
  #  images:
  #    migrator:
  #      path: ./prisma/Dockerfile
  environment:
    NODE_ENV: ${self:custom.node-env.${opt:stage}, 'local'}
    SLS_DEBUG: "*"
    LOG_LEVEL: info
    DATABASE_VENDOR: ${env:DATABASE_VENDOR}
    DATABASE_URL: ${env:DATABASE_URL}
    AUTH_VENDOR: ${env:AUTH_VENDOR}
    AUTH_AUDIENCE: ${env:AUTH_AUDIENCE}
    AUTH_ISSUER: ${env:AUTH_ISSUER}
    AUTH_DOMAIN: ${env:AUTH_DOMAIN}
    CLOUD_VENDOR: ${env:CLOUD_VENDOR}
    CLOUD_ACCESS_KEY_ID: ${env:CLOUD_ACCESS_KEY_ID}
    CLOUD_SECRET_ACCESS_KEY: ${env:CLOUD_SECRET_ACCESS_KEY}
    CLOUD_REGION: ${env:CLOUD_REGION}
    CLOUD_ENDPOINT: ${env:CLOUD_ENDPOINT}
    STORAGE_VENDOR: ${env:STORAGE_VENDOR}
    STORAGE_BUCKET: ${env:STORAGE_BUCKET}
custom:
  node-env:
    prod: "production"
    dev: "development"
    local: "local"
  serverless-offline:
    port: 3000
    stage: local
  serverlessPluginTypescript:
    tsConfigFileLocation: 'tsconfig.json'

functions:
  app:
    handler: src/main.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

  files:
    handler: src/file/index.handler
    events:
      - http:
          path: /files
          method: ANY
          cors: true
      - http:
          path: /files/{proxy+}
          method: ANY
          cors: true

  #migrator-docker:
  #  image:
  #    name: migrator
  #    command:
  #      - index.handler
  #  events:
  #    - httpApi: '*'
