export enum ErrorCode {
  INTERNAL_SERVER = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  CONFLICT = 'CONFLICT',
}
