export enum AuthErrorType {
  EMAIL_ALREADY_REGISTERED = "signUp.emailAlreadyRegistered",
  USER_NOT_FOUND = "signIn.userNotFound",
  PASSWORD_NOT_SET = "signIn.passwordNotSet",
  WRONG_PASSWORD = "signIn.wrongPassword",
  EMAIL_ALREADY_VERIFIED = "emailVerifiaction.alreadyVerified",
  EMAIL_CODE_NOT_EXPIRED = "emailVerification.notExpired",
  EMAIL_CODE_INVALID = "emailVerification.invalidCode",
  EMAIL_CODE_EXPIRED = "emailVerification.codeExpired",
  EMAIL_CODE_VERIFIED = "emailVerification.codeVerified",
  EMAIL_CODE_NOT_VERIFIED = "emailVerification.notVerified",
  PHONE_ALREADY_VERIFIED = "phoneVerification.alreadyVerified",
  PHONE_CODE_NOT_EXPIRED = "phoneVerification.notExpired",
  PHONE_CODE_INVALID = "phoneVerifiaction.invalidCode",
  PHONE_CODE_EXPIRED = "phoneVerification.codeExpired",
  PHONE_CODE_NOT_VERIFIED = "phoneVerification.notVerified",
  INVALID_REFRESH_TOKEN = "refreshToken.invalidRefreshToken",
  INVALID_TOKEN = "invalidToken",
  PASSWORDS_DOES_NOT_MATCH = "changePassword.passwordsDoesNotMatch",
}
