#Enviroments
@local_url = http://localhost:4000/graphql

POST {{local_url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL




curl localhost:4000/graphql \
  -F operations='{"query":"mutation UploadFile($file:Upload!) {\n photo_upload(file:$file)\n}”, “variables”: { “file”: null }", “variables”: { “file”: null }}' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@a.png

