#Enviroments
@local_url = http://localhost:4000/graphql

POST {{local_url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Create_user($input: create_user_input!) {
  create_user(input: $input) {
    id
    name
    role_name
    email
    created_at
    updated_at
  }
}

{
  "input": {
    "name": "Urle",
    "email": "urielsateles@gmail.com",
    "role_name": "TEST"
  }
}