name: 'me-mudei-api'

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command

      - uses: noliran/branch-based-secrets@v1
        with:
          secrets: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,TARGET_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME]}}
          aws-secret-access-key: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME]}}
          aws-region: ${{ secrets[env.AWS_REGION_NAME]}}

      - name: deploy me-mudei api
        run: npx serverless deploy --stage ${{ secrets[env.TARGET_ENV_NAME] }} --region ${{ secrets[env.AWS_REGION_NAME] }}
