name: STAG
on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm i

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAG_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAG_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.STAG_REGION }}

      - name: Serverless Install
        run: npm install -g serverless@^3

      - name: Serverless Deploy
        run: npx serverless
        env:
          DATABASE_URL: ${{ secrets.STAG_DATABASE_URL }}
